base_model: vinai/PhoGPT-7B5-Instruct
dataset: data/clean/health_qa_train.parquet
max_length: 1024

lora:
  lora_alpha: 8
  lora_dropout: 0.1
  r: 32
  bias: none
  task_type: CAUSAL_LM

training:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 5
  optim: paged_adamw_32bit
  save_steps: 50
  # logging_steps: 10
  logging_steps: 1
  learning_rate: 6.0e-5
  max_grad_norm: 0.3
  max_steps: 5
  # num_train_epochs: 3
  warmup_ratio: 0.03
  lr_scheduler_type: linear

  